#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
exec picom &
/home/alok/.config/polybar/launch.sh &
feh --bg-fill /home/alok/Wallpapers/wal1.jpg &
xsetroot -cursor_name left_ptr &
light -S 10 &
wmname alokwm &

bspc monitor -d Code Web Chat Music Files Misc

bspc config border_width         2
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#A3BE8C"
bspc config normal_border_color "#373d41"

bspc config external_rules_command "/home/alok/.config/bspwm/external_rules.sh"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state='floating'
bspc rule -a flameshot state='floating'
bspc rule -a feh state='floating'
